export type DefaultItem = {
  name: string;
  category: "camping" | "astro";
  sub_category: string | null;
  sort_order: number;
};

export const DEFAULT_STAR_PARTY_ITEMS: DefaultItem[] = [
  // Camping Gear
  { name: "Additional Pegs", category: "camping", sub_category: null, sort_order: 10 },
  { name: "Bed", category: "camping", sub_category: null, sort_order: 20 },
  { name: "Belagrava", category: "camping", sub_category: null, sort_order: 30 },
  { name: "Chair", category: "camping", sub_category: null, sort_order: 40 },
  { name: "Coat", category: "camping", sub_category: null, sort_order: 50 },
  { name: "Electric Hookup", category: "camping", sub_category: null, sort_order: 60 },
  { name: "Electric Grill", category: "camping", sub_category: null, sort_order: 70 },
  { name: "Electric Pump for Vacuum Bags", category: "camping", sub_category: null, sort_order: 80 },
  { name: "Eye Care", category: "camping", sub_category: null, sort_order: 90 },
  { name: "Fan Heater", category: "camping", sub_category: null, sort_order: 100 },
  { name: "Fridge and Adapter", category: "camping", sub_category: null, sort_order: 110 },
  { name: "Gloves", category: "camping", sub_category: null, sort_order: 120 },
  { name: "Ground Sheet", category: "camping", sub_category: null, sort_order: 130 },
  { name: "Hand Warmers", category: "camping", sub_category: null, sort_order: 140 },
  { name: "Hat", category: "camping", sub_category: null, sort_order: 150 },
  { name: "Hearing Aids", category: "camping", sub_category: null, sort_order: 160 },
  { name: "Hot Plate", category: "camping", sub_category: null, sort_order: 170 },
  { name: "Kettle", category: "camping", sub_category: null, sort_order: 180 },
  { name: "Leggings", category: "camping", sub_category: null, sort_order: 190 },
  { name: "Lighting", category: "camping", sub_category: null, sort_order: 200 },
  { name: "Mallet", category: "camping", sub_category: null, sort_order: 210 },
  { name: "Medication", category: "camping", sub_category: null, sort_order: 220 },
  { name: "Mirror", category: "camping", sub_category: null, sort_order: 230 },
  { name: "Oil Heater", category: "camping", sub_category: null, sort_order: 240 },
  { name: "Paracetamol", category: "camping", sub_category: null, sort_order: 250 },
  { name: "Phone Charger", category: "camping", sub_category: null, sort_order: 260 },
  { name: "Pillow x2", category: "camping", sub_category: null, sort_order: 270 },
  { name: "Plates, Cups & Cutlery", category: "camping", sub_category: null, sort_order: 280 },
  { name: "Power Bank", category: "camping", sub_category: null, sort_order: 290 },
  { name: "Pump", category: "camping", sub_category: null, sort_order: 300 },
  { name: "Sleep Band", category: "camping", sub_category: null, sort_order: 310 },
  { name: "Sleeping Bag", category: "camping", sub_category: null, sort_order: 320 },
  { name: "Sterident", category: "camping", sub_category: null, sort_order: 330 },
  { name: "Storage Cabinets x2", category: "camping", sub_category: null, sort_order: 340 },
  { name: "Straps (in case tent is wet)", category: "camping", sub_category: null, sort_order: 350 },
  { name: "Table", category: "camping", sub_category: null, sort_order: 360 },
  { name: "Tent", category: "camping", sub_category: null, sort_order: 370 },
  { name: "Tent Carpet", category: "camping", sub_category: null, sort_order: 380 },
  { name: "Thermal Socks", category: "camping", sub_category: null, sort_order: 390 },
  { name: "Toothbrush & Paste", category: "camping", sub_category: null, sort_order: 400 },
  { name: "Umbrella", category: "camping", sub_category: null, sort_order: 410 },
  { name: "Urine Bottle", category: "camping", sub_category: null, sort_order: 420 },
  { name: "USB Jacket", category: "camping", sub_category: null, sort_order: 430 },
  { name: "Walking Shoes", category: "camping", sub_category: null, sort_order: 440 },
  { name: "Wallet", category: "camping", sub_category: null, sort_order: 450 },
  { name: "Wash Towel & Shower Stuff", category: "camping", sub_category: null, sort_order: 460 },
  { name: "Washing Liquid / Cloth TT", category: "camping", sub_category: null, sort_order: 470 },
  { name: "Watch Charger", category: "camping", sub_category: null, sort_order: 480 },
  { name: "Waterproof Trousers", category: "camping", sub_category: null, sort_order: 490 },
  // Astro — Cameras
  { name: "174", category: "astro", sub_category: "Cameras", sort_order: 10 },
  { name: "585", category: "astro", sub_category: "Cameras", sort_order: 20 },
  { name: "26C", category: "astro", sub_category: "Cameras", sort_order: 30 },
  { name: "Canon", category: "astro", sub_category: "Cameras", sort_order: 40 },
  { name: "GM1", category: "astro", sub_category: "Cameras", sort_order: 50 },
  // Astro — Scopes
  { name: "CG1", category: "astro", sub_category: "Scopes", sort_order: 10 },
  { name: "ED80", category: "astro", sub_category: "Scopes", sort_order: 20 },
  { name: "Starwave", category: "astro", sub_category: "Scopes", sort_order: 30 },
  // Astro — Mounts
  { name: "AM", category: "astro", sub_category: "Mounts", sort_order: 10 },
  { name: "GTI", category: "astro", sub_category: "Mounts", sort_order: 20 },
  // Astro — Tripods
  { name: "EQ3", category: "astro", sub_category: "Tripods", sort_order: 10 },
  { name: "TC40", category: "astro", sub_category: "Tripods", sort_order: 20 },
  { name: "Pier Extension", category: "astro", sub_category: "Tripods", sort_order: 30 },
  { name: "Counter Weight & Bar", category: "astro", sub_category: "Tripods", sort_order: 40 },
  // Astro — Power Supplies
  { name: "Celestron Power Tank", category: "astro", sub_category: "Power Supplies", sort_order: 10 },
  { name: "Mains", category: "astro", sub_category: "Power Supplies", sort_order: 20 },
  { name: "Mains Lead", category: "astro", sub_category: "Power Supplies", sort_order: 30 },
  { name: "Power String Bag", category: "astro", sub_category: "Power Supplies", sort_order: 40 },
  { name: "Swary", category: "astro", sub_category: "Power Supplies", sort_order: 50 },
  // Astro — Controllers
  { name: "EQ3 Controller", category: "astro", sub_category: "Controllers", sort_order: 10 },
  { name: "Stellavita", category: "astro", sub_category: "Controllers", sort_order: 20 },
  // Astro — PC
  { name: "Laptop", category: "astro", sub_category: "PC", sort_order: 10 },
  { name: "Laptop Charger", category: "astro", sub_category: "PC", sort_order: 20 },
  { name: "Tablet", category: "astro", sub_category: "PC", sort_order: 30 },
  { name: "Android", category: "astro", sub_category: "PC", sort_order: 40 },
  { name: "Hard Drive", category: "astro", sub_category: "PC", sort_order: 50 },
  { name: "Monitor", category: "astro", sub_category: "PC", sort_order: 60 },
  { name: "Cross Over Cable", category: "astro", sub_category: "PC", sort_order: 70 },
  // Astro — General
  { name: "Cable Pack 1", category: "astro", sub_category: "General", sort_order: 10 },
  { name: "Cable Pack 2", category: "astro", sub_category: "General", sort_order: 20 },
  { name: "Android Phone", category: "astro", sub_category: "General", sort_order: 30 },
  { name: "Auto Focuser Touptek", category: "astro", sub_category: "General", sort_order: 40 },
  { name: "Black Bin Bags", category: "astro", sub_category: "General", sort_order: 50 },
  { name: "Blue Tape", category: "astro", sub_category: "General", sort_order: 60 },
  { name: "Celestron PB Charger", category: "astro", sub_category: "General", sort_order: 70 },
  { name: "Cigarette Extension", category: "astro", sub_category: "General", sort_order: 80 },
  { name: "Cigarette Splitter", category: "astro", sub_category: "General", sort_order: 90 },
  { name: "Extension Lead", category: "astro", sub_category: "General", sort_order: 100 },
  { name: "Flat Panel", category: "astro", sub_category: "General", sort_order: 110 },
  { name: "Glasses", category: "astro", sub_category: "General", sort_order: 120 },
  { name: "GPS Dongle", category: "astro", sub_category: "General", sort_order: 130 },
  { name: "Headtorch & Lead", category: "astro", sub_category: "General", sort_order: 140 },
  { name: "OCS Filters", category: "astro", sub_category: "General", sort_order: 150 },
  { name: "Spare Cables", category: "astro", sub_category: "General", sort_order: 160 },
  { name: "Telescope Covers", category: "astro", sub_category: "General", sort_order: 170 },
];
